"""Kalimat latih tambahan untuk model intent; digabung di chatbot."""

TRAINING_DATA_EXTRA = [
    # --- SALAM ---
    ("assalamualaikum", "salam"),
    ("selamat sore", "salam"),
    ("selamat malam", "salam"),
    ("permisi", "salam"),
    ("hai kak", "salam"),
    ("halo min", "salam"),
    ("halo admin", "salam"),
    ("yo", "salam"),
    ("sup", "salam"),
    ("whats up", "salam"),
    ("gimana kabarnya", "salam"),
    ("lg di mana", "salam"),
    ("lg apa", "salam"),
    ("hai bali guide", "salam"),
    ("halo guide", "salam"),
    ("selamat datang", "salam"),
    ("salam kenal", "salam"),
    ("perkenalkan nama saya budi", "salam"),
    ("hai ada yang bisa dibantu", "salam"),
    ("good morning", "salam"),
    ("good evening", "salam"),
    ("halo saya turis pertama kali ke bali", "salam"),
    ("hai saya butuh info wisata", "salam"),
    # --- PANTAI ---
    ("pengen ke pantai dong", "pantai"),
    ("ada pantai bagus gak", "pantai"),
    ("mau cari pantai sepi", "pantai"),
    ("pantai yang cocok buat anak", "pantai"),
    ("pantai untuk sunset bagus", "pantai"),
    ("rekomendasi beach club", "pantai"),
    ("spot foto di pantai", "pantai"),
    ("body rafting pantai", "pantai"),
    ("mau main jetski", "pantai"),
    ("pengen parasailing", "pantai"),
    ("kuta beach", "pantai"),
    ("double six beach", "pantai"),
    ("jimbaran sunset seafood", "pantai"),
    ("badung area pantai", "pantai"),
    ("nusa dua pantai", "pantai"),
    ("mau ke melasti beach", "pantai"),
    ("blue lagoon snorkel", "pantai"),
    ("amed snorkeling spot", "pantai"),
    ("virgin beach bali", "pantai"),
    ("pantai dengan ombak cocok surfing", "pantai"),
    ("belajar surfing pemula", "pantai"),
    ("pantai untuk bulan madu", "pantai"),
    ("mau lihat ombak besar", "pantai"),
    ("ke tebing pantai", "pantai"),
    ("pantai dengan pasir hitam", "pantai"),
    ("pantai hidden gem", "pantai"),
    ("best beach in bali", "pantai"),
    ("beach recommendation please", "pantai"),
    ("i want go to the beach", "pantai"),
    ("coastal area wisata", "pantai"),
    ("pesisir selatan bali", "pantai"),
    ("wisata bahari murah", "pantai"),
    ("kecapai sunset pantai", "pantai"),
    ("mau berjemur di pantai", "pantai"),
    ("pantai tidak ramai", "pantai"),
    ("pantai bersih ramah anak", "pantai"),
    ("rekomendasi pantai di selatan", "pantai"),
    ("pantai timur bali", "pantai"),
    ("pantai utara lovina", "pantai"),
    ("mau lihat lumba di pantai", "pantai"),
    ("spot cliff jumping pantai", "pantai"),
    ("pantai untuk yoga pagi", "pantai"),
    ("sunrise pantai timur", "pantai"),
    ("mau ke crystal bay", "pantai"),
    ("pantai diamond beach", "pantai"),
    ("kelingking beach", "pantai"),
    # --- ALAM ---
    ("gunung agung trekking", "alam"),
    ("trek ke crater batur", "alam"),
    ("sunrise campuhan ridge", "alam"),
    ("jalur trekking campuhan", "alam"),
    ("sawah terasering tegalalang", "alam"),
    ("jatiluwih sawah", "alam"),
    ("ke bukit teletubbies", "alam"),
    ("wisata goa gua", "alam"),
    ("goa lawah", "alam"),
    ("wisata danau buyan", "alam"),
    ("danau beratan bedugul", "alam"),
    ("hutan monyet ubud", "alam"),
    ("treetop adventure", "alam"),
    ("canyoning bali", "alam"),
    ("sepeda di sawah", "alam"),
    ("atv di area pedesaan", "alam"),
    ("wisata kebun raya", "alam"),
    ("edukasi pertanian organik", "alam"),
    ("mushroom bay nature", "alam"),
    ("pemandangan tebing karang", "alam"),
    ("tebing karang uluwatu", "alam"),
    ("wisata subak bali", "alam"),
    ("air terjun di utara", "alam"),
    ("air terjun gitgit", "alam"),
    ("sekumpul waterfall", "alam"),
    ("leke leke waterfall", "alam"),
    ("nature walk ubud", "alam"),
    ("green bali tour", "alam"),
    ("eco tourism bali", "alam"),
    ("jembatan gantung alam", "alam"),
    ("healing di hutan bambu", "alam"),
    ("spot sunrise di bukit", "alam"),
    ("daki gunung kecil", "alam"),
    ("outdoor activity seharian", "alam"),
    ("mau lihat terasering", "alam"),
    ("wisata petik salak", "alam"),
    ("agrowisata kopi", "alam"),
    ("kebun strawberry bedugul", "alam"),
    ("bird watching bali", "alam"),
    ("long walk di sawah", "alam"),
    ("village trekking", "alam"),
    ("river kayaking alam", "alam"),
    # --- BUDAYA ---
    ("tari barong", "budaya"),
    ("kecak fire dance", "budaya"),
    ("pura ulun danu", "budaya"),
    ("pura tanah lot", "budaya"),
    ("pura luhur uluwatu", "budaya"),
    ("upacara adat bali", "budaya"),
    ("odalan di pura", "budaya"),
    ("gamelan tradisional", "budaya"),
    ("workshop membuat canang", "budaya"),
    ("kelas dance bali", "budaya"),
    ("museum puri lukisan", "budaya"),
    ("museum arkeologi", "budaya"),
    ("desa adat penglipuran", "budaya"),
    ("tenganan village", "budaya"),
    ("heritage tour ubud", "budaya"),
    ("cerita legenda bali", "budaya"),
    ("wisata spiritual", "budaya"),
    ("yoga retreat budaya", "budaya"),
    ("temple dress code", "budaya"),
    ("sarung ke pura", "budaya"),
    ("ngaben ceremony view", "budaya"),
    ("festival budaya bali", "budaya"),
    ("seni ukir kayu", "budaya"),
    ("batik workshop bali", "budaya"),
    ("kuliah singkat sejarah bali", "budaya"),
    ("kunjungi istana", "budaya"),
    ("water palace tirtagangga", "budaya"),
    ("taman ujung karangasem", "budaya"),
    ("gwk culture park", "budaya"),
    ("pertunjukan debus", "budaya"),
    ("legong dance show", "budaya"),
    ("pelinggih pura", "budaya"),
    # --- KULINER ---
    ("bebek betutu", "kuliner"),
    ("babi guling khas", "kuliner"),
    ("nasi campur bali", "kuliner"),
    ("warung nasi pedas", "kuliner"),
    ("night market sanur", "kuliner"),
    ("street food legian", "kuliner"),
    ("food tour ubud", "kuliner"),
    ("fine dining seminyak", "kuliner"),
    ("rooftop bar kuta", "kuliner"),
    ("wine pairing dinner", "kuliner"),
    ("vegan restaurant bali", "kuliner"),
    ("healthy bowl canggu", "kuliner"),
    ("smoothie bowl", "kuliner"),
    ("luwak coffee tasting", "kuliner"),
    ("plantation coffee tour", "kuliner"),
    ("traditional market badung", "kuliner"),
    ("oleh oleh pie susu", "kuliner"),
    ("keripik singkong bali", "kuliner"),
    ("sate lilit ikan", "kuliner"),
    ("lawar bali", "kuliner"),
    ("rujak bulung", "kuliner"),
    ("es daluman", "kuliner"),
    ("klepon dan jajanan pasar", "kuliner"),
    ("brunch spot canggu", "kuliner"),
    ("seafood jimbaran malam", "kuliner"),
    ("bbq pantai", "kuliner"),
    ("buffet hotel", "kuliner"),
    ("degustation menu", "kuliner"),
    ("kuliner halal di bali", "kuliner"),
    ("restoran family friendly", "kuliner"),
    ("food blogger spot", "kuliner"),
    ("hidden cafe ubud", "kuliner"),
    ("bakery artisan sanur", "kuliner"),
    ("wine bar ubud", "kuliner"),
    ("cocktail bar seminyak", "kuliner"),
    ("pub live music", "kuliner"),
    ("warung lokal murah", "kuliner"),
    ("test kitchen fusion", "kuliner"),
    ("farm to table dining", "kuliner"),
    # --- HIBURAN ---
    ("waterbom bali tiket", "hiburan"),
    ("finns beach club party", "hiburan"),
    ("potato head events", "hiburan"),
    ("beach club pool party", "hiburan"),
    ("nightclub legian", "hiburan"),
    ("karaoke denpasar", "hiburan"),
    ("bowling family", "hiburan"),
    ("trampoline park", "hiburan"),
    ("escape room bali", "hiburan"),
    ("paintball outdoor", "hiburan"),
    ("flying fox panjang", "hiburan"),
    ("balinese dance dinner", "hiburan"),
    ("gwk show malam", "hiburan"),
    ("sunset point club", "hiburan"),
    ("day club pool", "hiburan"),
    ("boat party", "hiburan"),
    ("sunset cruise", "hiburan"),
    ("dolphin tour pagi", "hiburan"),
    ("glass bottom boat", "hiburan"),
    ("banana boat ride", "hiburan"),
    ("flyboard water sport", "hiburan"),
    ("jetski rental", "hiburan"),
    ("submarine odyssey", "hiburan"),
    ("bird park bali", "hiburan"),
    ("zoo safari", "hiburan"),
    ("reptile park", "hiburan"),
    ("elephant safari", "hiburan"),
    ("marine walk", "hiburan"),
    ("seawalker sanur", "hiburan"),
    ("underwater scooter", "hiburan"),
    ("paragliding bukit", "hiburan"),
    ("microlight flying", "hiburan"),
    ("fun ride atv beach", "hiburan"),
    ("bumper boat", "hiburan"),
    ("circus show", "hiburan"),
    ("theme park anak", "hiburan"),
    ("kidzone indoor", "hiburan"),
    ("permainan air ekstrem", "hiburan"),
    ("wahana roller coaster mini", "hiburan"),
    # --- MURAH ---
    ("duit pas pas", "murah"),
    ("dompet tipis", "murah"),
    ("mahasiswa budget minim", "murah"),
    ("cari tiket under 50k", "murah"),
    ("entrance fee murah", "murah"),
    ("gratis masuk kalau bisa", "murah"),
    ("hemat biaya transport", "murah"),
    ("ngirit banget", "murah"),
    ("irit budget", "murah"),
    ("backpacker style", "murah"),
    ("hostel murah area", "murah"),
    ("wisata tanpa bayar parkir mahal", "murah"),
    ("diskon tiket", "murah"),
    ("promo tiket wisata", "murah"),
    ("paket hemat keluarga", "murah"),
    ("liburan ala backpacker", "murah"),
    ("duit cuma sejuta", "murah"),
    ("ga mau bayar mahal", "murah"),
    ("yang penting murah", "murah"),
    ("spot foto gratis", "murah"),
    ("hidden spot tanpa tiket", "murah"),
    ("public beach free", "murah"),
    ("hemat bensin rute", "murah"),
    ("sharing cost tour", "murah"),
    ("carpool murah", "murah"),
    # --- TERBAIK ---
    ("top 10 destinasi", "terbaik"),
    ("ranking wisata favorit", "terbaik"),
    ("paling recommended versi netizen", "terbaik"),
    ("destinasi ikonik bali", "terbaik"),
    ("bucket list bali", "terbaik"),
    ("must visit once", "terbaik"),
    ("signature spot bali", "terbaik"),
    ("instagram viral place", "terbaik"),
    ("trending wisata 2026", "terbaik"),
    ("highlight tour bali", "terbaik"),
    ("juara destinasi", "terbaik"),
    ("pemenang tripadvisor", "terbaik"),
    ("rating tinggi wisata", "terbaik"),
    ("bintang lima pengalaman", "terbaik"),
    ("the best of bali", "terbaik"),
    ("ikon pariwisata", "terbaik"),
    ("unforgettable place", "terbaik"),
    ("prime destination", "terbaik"),
    ("flagship attraction", "terbaik"),
    ("most photographed", "terbaik"),
    ("landmark wajib foto", "terbaik"),
    ("tempat legendaris", "terbaik"),
    ("legenda wisata bali", "terbaik"),
    ("spot terkenal dunia", "terbaik"),
    ("world famous beach", "terbaik"),
    ("award winning resort area", "terbaik"),
    # --- LOKASI BADUNG ---
    ("kelegian wisata", "lokasi_badung"),
    ("mau area kuta", "lokasi_badung"),
    ("penginapan di seminyak", "lokasi_badung"),
    ("canggu digital nomad spot", "lokasi_badung"),
    ("pecatu cliff", "lokasi_badung"),
    ("jimbaran seafood night", "lokasi_badung"),
    ("taman ayun dekat badung", "lokasi_badung"),
    ("garuda wisnu kencana area", "lokasi_badung"),
    ("dreamland beach zone", "lokasi_badung"),
    ("bingin beach surf", "lokasi_badung"),
    ("padang padang beach", "lokasi_badung"),
    ("suluban beach", "lokasi_badung"),
    ("ungasan resort", "lokasi_badung"),
    ("benoa watersport", "lokasi_badung"),
    ("serangan island trip", "lokasi_badung"),
    ("kurama wisata badung", "lokasi_badung"),
    ("petitenget area club", "lokasi_badung"),
    ("batu bolong canggu", "lokasi_badung"),
    ("echo beach sunset", "lokasi_badung"),
    ("berawa beach", "lokasi_badung"),
    # --- LOKASI GIANYAR ---
    ("seni ubud painting", "lokasi_gianyar"),
    ("monkey forest sanctuary", "lokasi_gianyar"),
    ("ubud art market", "lokasi_gianyar"),
    ("goa gajah gianyar", "lokasi_gianyar"),
    ("elephant cave ubud", "lokasi_gianyar"),
    ("yoga barn area", "lokasi_gianyar"),
    ("celuk silver village", "lokasi_gianyar"),
    ("mas wood carving", "lokasi_gianyar"),
    ("batuan painting village", "lokasi_gianyar"),
    ("sukawati art market", "lokasi_gianyar"),
    ("tegalalang swing", "lokasi_gianyar"),
    ("aloha ubud swing", "lokasi_gianyar"),
    ("payangan rafting start", "lokasi_gianyar"),
    ("kemenuh butterfly", "lokasi_gianyar"),
    ("bali zoo gianyar", "lokasi_gianyar"),
    ("bird park gianyar", "lokasi_gianyar"),
    ("safari marine gianyar", "lokasi_gianyar"),
    ("night safari gianyar", "lokasi_gianyar"),
    ("sidemen valley view", "lokasi_gianyar"),
    ("rendang village quiet", "lokasi_gianyar"),
    ("pejeng historical", "lokasi_gianyar"),
    # --- LOKASI DENPASAR ---
    ("pusat kota denpasar", "lokasi_denpasar"),
    ("badung traditional market", "lokasi_denpasar"),
    ("sanur morning walk", "lokasi_denpasar"),
    ("mertasari beach sanur", "lokasi_denpasar"),
    ("lebih beach sanur", "lokasi_denpasar"),
    ("bajra sandhi museum", "lokasi_denpasar"),
    ("art center denpasar", "lokasi_denpasar"),
    ("pasar burung denpasar", "lokasi_denpasar"),
    ("lapangan puputan", "lokasi_denpasar"),
    ("mall denpasar", "lokasi_denpasar"),
    ("sidakarya temple area", "lokasi_denpasar"),
    ("serangan mangrove", "lokasi_denpasar"),
    ("conservation turtle sanur", "lokasi_denpasar"),
    ("segara ayu sanur", "lokasi_denpasar"),
    ("hyatt reef sanur", "lokasi_denpasar"),
    # --- LOKASI KARANGASEM ---
    ("tirta gangga air suci", "lokasi_karangasem"),
    ("lahangan sweet view", "lokasi_karangasem"),
    ("lempuyang gate heaven", "lokasi_karangasem"),
    ("tulamben dive wreck", "lokasi_karangasem"),
    ("amed beach chill", "lokasi_karangasem"),
    ("jasmine dive amed", "lokasi_karangasem"),
    ("candidasa snorkeling", "lokasi_karangasem"),
    ("blue lagoon padangbai", "lokasi_karangasem"),
    ("bias tugel padangbai", "lokasi_karangasem"),
    ("virgin beach karangasem", "lokasi_karangasem"),
    ("selang blangah waterfall", "lokasi_karangasem"),
    ("besakih mother temple route", "lokasi_karangasem"),
    ("sidemen rice terrace", "lokasi_karangasem"),
    ("bukit asah karangasem", "lokasi_karangasem"),
    ("lahangan hill camping", "lokasi_karangasem"),
    ("jasri beach secret", "lokasi_karangasem"),
    ("usaha dive amed", "lokasi_karangasem"),
    ("japanese shipwreck amed", "lokasi_karangasem"),
    ("lipah bay amed", "lokasi_karangasem"),
    # --- LOKASI BULELENG ---
    ("gitgit waterfall north", "lokasi_buleleng"),
    ("sekumpul trekking north", "lokasi_buleleng"),
    ("lovina dolphin sunrise", "lokasi_buleleng"),
    ("banjar hot spring", "lokasi_buleleng"),
    ("brahma vihara banjar", "lokasi_buleleng"),
    ("air sanih natural pool", "lokasi_buleleng"),
    ("yeh mampeh waterfall", "lokasi_buleleng"),
    ("singaraja old town", "lokasi_buleleng"),
    ("museum buleleng", "lokasi_buleleng"),
    ("west bali national park", "lokasi_buleleng"),
    ("menjangan island dive", "lokasi_buleleng"),
    ("gilimanuk ferry port", "lokasi_buleleng"),
    ("pemutaran coral reef", "lokasi_buleleng"),
    ("puri singaraja heritage", "lokasi_buleleng"),
    ("meduwe karang temple", "lokasi_buleleng"),
    ("beji temple singaraja", "lokasi_buleleng"),
    ("hidden canyon beji", "lokasi_buleleng"),
    ("krisna oleh oleh buleleng", "lokasi_buleleng"),
    ("busungbiu rice view", "lokasi_buleleng"),
    # --- LOKASI TABANAN ---
    ("jati luwi hiking", "lokasi_tabanan"),
    ("batukaru temple jungle", "lokasi_tabanan"),
    ("alis jungle resort route", "lokasi_tabanan"),
    ("tanah lot sunset icon", "lokasi_tabanan"),
    ("kedaton monkey forest tabanan", "lokasi_tabanan"),
    ("bali butterfly park tabanan", "lokasi_tabanan"),
    ("pupuan vegetable terraces", "lokasi_tabanan"),
    ("munduk waterfall hike", "lokasi_tabanan"),
    ("blingbling waterfall", "lokasi_tabanan"),
    ("handara gate photo", "lokasi_tabanan"),
    ("ulun danu iconic tabanan", "lokasi_tabanan"),
    ("mengwi taman ayun", "lokasi_tabanan"),
    ("sangeh monkey forest", "lokasi_tabanan"),
    ("pererenan beach tabanan", "lokasi_tabanan"),
    ("yeh gangga beach", "lokasi_tabanan"),
    ("ecogreen park tabanan", "lokasi_tabanan"),
    ("subak museum tabanan", "lokasi_tabanan"),
    # --- LOKASI BANGLI ---
    ("trunyan village unusual", "lokasi_bangli"),
    ("batur natural hot spring", "lokasi_bangli"),
    ("pinggan village sunrise", "lokasi_bangli"),
    ("kintamani coffee view", "lokasi_bangli"),
    ("toya devasya hot spring", "lokasi_bangli"),
    ("lake batur boat", "lokasi_bangli"),
    ("mount batur jeep sunrise", "lokasi_bangli"),
    ("black lava jeep tour", "lokasi_bangli"),
    ("ulundanu batur temple", "lokasi_bangli"),
    ("penelokan view point", "lokasi_bangli"),
    ("songan village farming", "lokasi_bangli"),
    ("kintamani organic farm", "lokasi_bangli"),
    ("batur geo park", "lokasi_bangli"),
    ("bumi langit permaculture", "lokasi_bangli"),
    ("sidemen compared bangli", "lokasi_bangli"),
    ("bangli general nature", "lokasi_bangli"),
    # --- LOKASI KLUNGKUNG ---
    ("atuh beach nusa penida", "lokasi_klungkung"),
    ("kelingking cliff penida", "lokasi_klungkung"),
    ("broken beach angel billabong", "lokasi_klungkung"),
    ("crystal bay snorkel penida", "lokasi_klungkung"),
    ("manta point diving", "lokasi_klungkung"),
    ("suwehan beach penida", "lokasi_klungkung"),
    ("diamond beach stairway", "lokasi_klungkung"),
    ("peguyangan waterfall blue stairs", "lokasi_klungkung"),
    ("tembeling natural pool", "lokasi_klungkung"),
    ("nusa lembongan day trip", "lokasi_klungkung"),
    ("yellow bridge lembongan", "lokasi_klungkung"),
    ("mushroom bay lembongan", "lokasi_klungkung"),
    ("devils tear lembongan", "lokasi_klungkung"),
    ("semarapura klungkung palace", "lokasi_klungkung"),
    ("kertha gosa justice hall", "lokasi_klungkung"),
    ("goa lawah klungkung route", "lokasi_klungkung"),
    ("hidden canyon guwang", "lokasi_klungkung"),
    ("taman sari guwang", "lokasi_klungkung"),
    ("nusa ceningan blue lagoon", "lokasi_klungkung"),
    ("seaweed farm lembongan", "lokasi_klungkung"),
    # --- LOKASI JEMBRANA ---
    ("negara city west bali", "lokasi_jembrana"),
    ("medewi longboard surf", "lokasi_jembrana"),
    ("delod berawah beach", "lokasi_jembrana"),
    ("balian river mouth surf", "lokasi_jembrana"),
    ("pemuatan rice terrace jembrana", "lokasi_jembrana"),
    ("rambut siwi temple ocean", "lokasi_jembrana"),
    ("bunut bolong giant tree", "lokasi_jembrana"),
    ("west bali coast drive", "lokasi_jembrana"),
    ("gilimanuk to menjangan route", "lokasi_jembrana"),
    ("melaya beach fishing village", "lokasi_jembrana"),
    ("pantai perancak jembrana", "lokasi_jembrana"),
    ("jembrana slow trip", "lokasi_jembrana"),
    ("krama desa jembrana", "lokasi_jembrana"),
    ("dolphin watching west secret", "lokasi_jembrana"),
    ("estuary mangrove jembrana", "lokasi_jembrana"),
    ("traditional buffalo race info", "lokasi_jembrana"),
    ("makepung race culture", "lokasi_jembrana"),
    ("hidden waterfall jembrana", "lokasi_jembrana"),
    ("west national park entry jembrana", "lokasi_jembrana"),
    # --- LANJUT ---
    ("ganti rekomendasi", "lanjut"),
    ("next recommendation", "lanjut"),
    ("tempat lain dong", "lanjut"),
    ("kurang suka yang tadi", "lanjut"),
    ("coba yang beda", "lanjut"),
    ("list lainnya", "lanjut"),
    ("scroll destinasi berikutnya", "lanjut"),
    ("skip yang ini", "lanjut"),
    ("bukan itu maksudnya", "lanjut"),
    ("ga cocok", "lanjut"),
    ("next please", "lanjut"),
    ("show more places", "lanjut"),
    ("expand options", "lanjut"),
    ("alternatif wisata", "lanjut"),
    ("pilihan cadangan", "lanjut"),
    ("rekomendasi berikutnya", "lanjut"),
    ("lanjut list nomor 5", "lanjut"),
    ("ada spot lain", "lanjut"),
    ("variasi destinasi", "lanjut"),
    ("random lagi", "lanjut"),
    ("shuffle destinasi", "lanjut"),
    ("urutan baru", "lanjut"),
    # --- TERIMA KASIH ---
    ("thank you banget", "terima_kasih"),
    ("thanks ya kak", "terima_kasih"),
    ("makasih banyak bantuannya", "terima_kasih"),
    ("suksma", "terima_kasih"),
    ("matursuwun", "terima_kasih"),
    ("appreciate it", "terima_kasih"),
    ("cheers mate", "terima_kasih"),
    ("nice info thanks", "terima_kasih"),
    ("mantap infonya", "terima_kasih"),
    ("oke sip makasih", "terima_kasih"),
    ("thank u so much", "terima_kasih"),
    ("grateful for help", "terima_kasih"),
    ("god bless thanks", "terima_kasih"),
    ("trimakasih ya", "terima_kasih"),
    ("makaci", "terima_kasih"),
    ("tq ya", "terima_kasih"),
    ("tyvm", "terima_kasih"),
    ("thankyou bro", "terima_kasih"),
    ("nice one thanks", "terima_kasih"),
    ("okee berarti gitu thanks", "terima_kasih"),
    ("thanks sudah jelasin", "terima_kasih"),
    ("makasih udah dirangkum", "terima_kasih"),
    ("thank you for recommendation", "terima_kasih"),
    # --- BANTUAN ---
    ("bingung pilih itinerary", "bantuan"),
    ("tolong susun rute 3 hari", "bantuan"),
    ("gak tau mau kemana hari ini", "bantuan"),
    ("butuh saran darurat", "bantuan"),
    ("ada ide weekend", "bantuan"),
    ("random suggestion dong", "bantuan"),
    ("surprise me", "bantuan"),
    ("bantu itinerary honeymoon", "bantuan"),
    ("family trip bingung", "bantuan"),
    ("anak bosan di hotel", "bantuan"),
    ("cuaca mendung mau kemana", "bantuan"),
    ("macet di kuta alternatif", "bantuan"),
    ("ga bisa sewa motor kemana", "bantuan"),
    ("pertama kali ke bali clueless", "bantuan"),
    ("tur dari jakarta gak tau jadwal", "bantuan"),
    ("open trip recommendation", "bantuan"),
    ("guide lokal butuh rekomendasi", "bantuan"),
    ("saran hemat waktu", "bantuan"),
    ("optimize route harian", "bantuan"),
    ("tolong bandingkan ubud vs sanur", "bantuan"),
    ("mana lebih worth penida", "bantuan"),
    ("help compare beaches", "bantuan"),
    ("need advice jam buka", "bantuan"),
    ("info dress code pura", "bantuan"),
    ("safety tips snorkeling", "bantuan"),
    ("tips anti scam taxi", "bantuan"),
    ("bingung bedanya swing ubud", "bantuan"),
    ("gatau bedanya pasar sukawati", "bantuan"),
    ("pusing crowd management", "bantuan"),
    ("stress cari parkir", "bantuan"),
    ("help urgent toilet spot", "bantuan"),
    ("tolong cari warung halal", "bantuan"),
    ("where to change money safe", "bantuan"),
    # --- JAWABAN PROFIL ---
    ("budget hemat aja", "jawaban_profil"),
    ("duit saya terbatas", "jawaban_profil"),
    ("milih yang sedang harga tiketnya", "jawaban_profil"),
    ("budget premium gapapa", "jawaban_profil"),
    ("ga masalah mahal", "jawaban_profil"),
    ("suka banget jalan kaki", "jawaban_profil"),
    ("suka naik motor explore", "jawaban_profil"),
    ("senang shoping oleh oleh", "jawaban_profil"),
    ("lebih suka sunrise dibanding sunset", "jawaban_profil"),
    ("suka yoga pagi", "jawaban_profil"),
    ("suka spa dan massage", "jawaban_profil"),
    ("senang melihat sunset romantis", "jawaban_profil"),
    ("mood lagi pengen healing", "jawaban_profil"),
    ("lagi pengen party malam", "jawaban_profil"),
    ("suka tempat ramai orang", "jawaban_profil"),
    ("suasana sepi dan tenang", "jawaban_profil"),
    ("pergi sama orang tua", "jawaban_profil"),
    ("trip sama pasangan honeymoon", "jawaban_profil"),
    ("bareng teman kantor", "jawaban_profil"),
    ("rombongan kampus", "jawaban_profil"),
    ("anak saya umur 5 tahun", "jawaban_profil"),
    ("punya bayi 1 tahun", "jawaban_profil"),
    ("kaki saya lemah jalan jauh susah", "jawaban_profil"),
    ("suka trek pendek saja", "jawaban_profil"),
    ("suka hiking berjam jam", "jawaban_profil"),
    ("prefer gojek kemana mana", "jawaban_profil"),
    ("mobilitas saya terbatas kursi roda", "jawaban_profil"),
    ("mobility santai aja", "jawaban_profil"),
    ("suka spot foto drone", "jawaban_profil"),
    ("senang live music malam", "jawaban_profil"),
    ("suka belajar sejarah lokal", "jawaban_profil"),
    ("pengen culinary tour seharian", "jawaban_profil"),
    ("suka kuliner pedas", "jawaban_profil"),
    ("prefer makan seafood", "jawaban_profil"),
    ("vegetarian strict", "jawaban_profil"),
    ("halal food only", "jawaban_profil"),
    ("tidak suka keramaian kuta", "jawaban_profil"),
    ("prefer daerah ubud tenang", "jawaban_profil"),
    ("pengen area sanur family", "jawaban_profil"),
    ("penginapan sudah di nusa dua", "jawaban_profil"),
    ("hotel saya di legian", "jawaban_profil"),
    ("base camp di candidasa", "jawaban_profil"),
    ("mau explore utara dulu", "jawaban_profil"),
    ("fokus ke nusa penida 2 hari", "jawaban_profil"),
    ("ga bisa renang tapi mau pantai", "jawaban_profil"),
    ("takut ketinggian tapi mau view", "jawaban_profil"),
    ("anak suka binatang", "jawaban_profil"),
    ("butuh tempat playground", "jawaban_profil"),
    ("trip type keluarga besar", "jawaban_profil"),
    ("budget sedang saja", "jawaban_profil"),
    ("maunya mood adventure", "jawaban_profil"),
    ("maunya mood romantis", "jawaban_profil"),
]
